Tomado del texto guía

In [2]:
import autograd.numpy as np
from autograd import grad, jacobian

In [3]:
p = np.array([1, 2, 3], dtype=float)
def f(x): # Objective function
    return 2*x[0]*x[1]**3+3*x[1]**2*x[2]+x[2]**3*x[0]
grad_f = grad(f) # gradient of the objective function
hessian_f = jacobian(grad_f) # Hessian of the objective function

print("gradient vector:",grad_f(p))

gradient vector: [43. 60. 39.]


In [4]:
print("Hessian matrix:\n",hessian_f(p))

Hessian matrix:
 [[ 0. 24. 27.]
 [24. 42. 12.]
 [27. 12. 18.]]
